### ISSUE TITLE
YouTube Videos in VRBO Images Breaking Code

### ISSUE THREAD

**Issue by pcifaldi** [Zorro6191/vrbo-bulk-image-scrapper#1]
Awesome that you just posted this, because I am looking to scrape multiple VRBO listings for images!

I got everything running on MacOS, the first few images download to the folder as planned, as soon as I get to a YouTube video in the VRBO listing's photos it breaks. I don't need to download the YouTube videos. Not sure how to get around this...

Try listing 24587 as an example.

Thanks,

Paul

**Comment by Minhaj-Mumtaz** [comment]
Thank you for the feedback, I just fixed the issue.
